### ISSUE TITLE
feedmaker issues when generating feeds from linkedin

### ISSUE THREAD

**Issue by kobolibra** [kevinschaul/feedmaker#2]
First of all, I would like to express my gratitude for this great feedmaker tool. It has been such a great help.

So I have been using it to generate job feeds from Linkedin for some time. It might be sg.linkedin.com, hk.linkedin.com or cn.linkedin.com, depending on where the advertised job is located. Everything works fine until recently when some of the feeds are frequently generated as some *****, which means nothing was populated. I am not sure why but wondering the access might have been blocked by linkedin there. I have attached a screenshot for easier reference. Could you kindly help to advise how I could get this fixed? Thank you.
<img width="894" alt="截屏2024-12-17 17 03 37" src="https://github.com/user-attachments/assets/06abe1a7-95ac-498f-980f-fafac9bbedf5" />

**Comment by kevinschaul** [comment]
Hi and glad you like the tool! Unfortunately I am not sure why that has happened. You could try hosting your own instance of feedmaker. Short of that I don't think I can help, sorry.

**Comment by kobolibra** [comment]
Thank you Kevin for your reply. Well noted on this.

A great day ahead.


Sent from Outlook<http://aka.ms/weboutlook>
________________________________
